apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: My-Test-Techdocs-v1.o
  description: testing techdocs implementations
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/Prasun117/test-component-techdocs-v1.0
  tags:
    - techdocs
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
